// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/appuser-middleware/pkg/db/ent/appoauththirdparty"
	"github.com/NpoolPlatform/appuser-middleware/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// AppOAuthThirdPartyQuery is the builder for querying AppOAuthThirdParty entities.
type AppOAuthThirdPartyQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AppOAuthThirdParty
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AppOAuthThirdPartyQuery builder.
func (aotpq *AppOAuthThirdPartyQuery) Where(ps ...predicate.AppOAuthThirdParty) *AppOAuthThirdPartyQuery {
	aotpq.predicates = append(aotpq.predicates, ps...)
	return aotpq
}

// Limit adds a limit step to the query.
func (aotpq *AppOAuthThirdPartyQuery) Limit(limit int) *AppOAuthThirdPartyQuery {
	aotpq.limit = &limit
	return aotpq
}

// Offset adds an offset step to the query.
func (aotpq *AppOAuthThirdPartyQuery) Offset(offset int) *AppOAuthThirdPartyQuery {
	aotpq.offset = &offset
	return aotpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aotpq *AppOAuthThirdPartyQuery) Unique(unique bool) *AppOAuthThirdPartyQuery {
	aotpq.unique = &unique
	return aotpq
}

// Order adds an order step to the query.
func (aotpq *AppOAuthThirdPartyQuery) Order(o ...OrderFunc) *AppOAuthThirdPartyQuery {
	aotpq.order = append(aotpq.order, o...)
	return aotpq
}

// First returns the first AppOAuthThirdParty entity from the query.
// Returns a *NotFoundError when no AppOAuthThirdParty was found.
func (aotpq *AppOAuthThirdPartyQuery) First(ctx context.Context) (*AppOAuthThirdParty, error) {
	nodes, err := aotpq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{appoauththirdparty.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aotpq *AppOAuthThirdPartyQuery) FirstX(ctx context.Context) *AppOAuthThirdParty {
	node, err := aotpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AppOAuthThirdParty ID from the query.
// Returns a *NotFoundError when no AppOAuthThirdParty ID was found.
func (aotpq *AppOAuthThirdPartyQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aotpq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{appoauththirdparty.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aotpq *AppOAuthThirdPartyQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := aotpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AppOAuthThirdParty entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AppOAuthThirdParty entity is found.
// Returns a *NotFoundError when no AppOAuthThirdParty entities are found.
func (aotpq *AppOAuthThirdPartyQuery) Only(ctx context.Context) (*AppOAuthThirdParty, error) {
	nodes, err := aotpq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{appoauththirdparty.Label}
	default:
		return nil, &NotSingularError{appoauththirdparty.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aotpq *AppOAuthThirdPartyQuery) OnlyX(ctx context.Context) *AppOAuthThirdParty {
	node, err := aotpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AppOAuthThirdParty ID in the query.
// Returns a *NotSingularError when more than one AppOAuthThirdParty ID is found.
// Returns a *NotFoundError when no entities are found.
func (aotpq *AppOAuthThirdPartyQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aotpq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{appoauththirdparty.Label}
	default:
		err = &NotSingularError{appoauththirdparty.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aotpq *AppOAuthThirdPartyQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := aotpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AppOAuthThirdParties.
func (aotpq *AppOAuthThirdPartyQuery) All(ctx context.Context) ([]*AppOAuthThirdParty, error) {
	if err := aotpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return aotpq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (aotpq *AppOAuthThirdPartyQuery) AllX(ctx context.Context) []*AppOAuthThirdParty {
	nodes, err := aotpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AppOAuthThirdParty IDs.
func (aotpq *AppOAuthThirdPartyQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := aotpq.Select(appoauththirdparty.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aotpq *AppOAuthThirdPartyQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := aotpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aotpq *AppOAuthThirdPartyQuery) Count(ctx context.Context) (int, error) {
	if err := aotpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return aotpq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (aotpq *AppOAuthThirdPartyQuery) CountX(ctx context.Context) int {
	count, err := aotpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aotpq *AppOAuthThirdPartyQuery) Exist(ctx context.Context) (bool, error) {
	if err := aotpq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return aotpq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (aotpq *AppOAuthThirdPartyQuery) ExistX(ctx context.Context) bool {
	exist, err := aotpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AppOAuthThirdPartyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aotpq *AppOAuthThirdPartyQuery) Clone() *AppOAuthThirdPartyQuery {
	if aotpq == nil {
		return nil
	}
	return &AppOAuthThirdPartyQuery{
		config:     aotpq.config,
		limit:      aotpq.limit,
		offset:     aotpq.offset,
		order:      append([]OrderFunc{}, aotpq.order...),
		predicates: append([]predicate.AppOAuthThirdParty{}, aotpq.predicates...),
		// clone intermediate query.
		sql:    aotpq.sql.Clone(),
		path:   aotpq.path,
		unique: aotpq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AppOAuthThirdParty.Query().
//		GroupBy(appoauththirdparty.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (aotpq *AppOAuthThirdPartyQuery) GroupBy(field string, fields ...string) *AppOAuthThirdPartyGroupBy {
	grbuild := &AppOAuthThirdPartyGroupBy{config: aotpq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := aotpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return aotpq.sqlQuery(ctx), nil
	}
	grbuild.label = appoauththirdparty.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.AppOAuthThirdParty.Query().
//		Select(appoauththirdparty.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (aotpq *AppOAuthThirdPartyQuery) Select(fields ...string) *AppOAuthThirdPartySelect {
	aotpq.fields = append(aotpq.fields, fields...)
	selbuild := &AppOAuthThirdPartySelect{AppOAuthThirdPartyQuery: aotpq}
	selbuild.label = appoauththirdparty.Label
	selbuild.flds, selbuild.scan = &aotpq.fields, selbuild.Scan
	return selbuild
}

func (aotpq *AppOAuthThirdPartyQuery) prepareQuery(ctx context.Context) error {
	for _, f := range aotpq.fields {
		if !appoauththirdparty.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aotpq.path != nil {
		prev, err := aotpq.path(ctx)
		if err != nil {
			return err
		}
		aotpq.sql = prev
	}
	if appoauththirdparty.Policy == nil {
		return errors.New("ent: uninitialized appoauththirdparty.Policy (forgotten import ent/runtime?)")
	}
	if err := appoauththirdparty.Policy.EvalQuery(ctx, aotpq); err != nil {
		return err
	}
	return nil
}

func (aotpq *AppOAuthThirdPartyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AppOAuthThirdParty, error) {
	var (
		nodes = []*AppOAuthThirdParty{}
		_spec = aotpq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*AppOAuthThirdParty).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &AppOAuthThirdParty{config: aotpq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(aotpq.modifiers) > 0 {
		_spec.Modifiers = aotpq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aotpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (aotpq *AppOAuthThirdPartyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aotpq.querySpec()
	if len(aotpq.modifiers) > 0 {
		_spec.Modifiers = aotpq.modifiers
	}
	_spec.Node.Columns = aotpq.fields
	if len(aotpq.fields) > 0 {
		_spec.Unique = aotpq.unique != nil && *aotpq.unique
	}
	return sqlgraph.CountNodes(ctx, aotpq.driver, _spec)
}

func (aotpq *AppOAuthThirdPartyQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := aotpq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (aotpq *AppOAuthThirdPartyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appoauththirdparty.Table,
			Columns: appoauththirdparty.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appoauththirdparty.FieldID,
			},
		},
		From:   aotpq.sql,
		Unique: true,
	}
	if unique := aotpq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := aotpq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appoauththirdparty.FieldID)
		for i := range fields {
			if fields[i] != appoauththirdparty.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aotpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aotpq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aotpq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aotpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aotpq *AppOAuthThirdPartyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aotpq.driver.Dialect())
	t1 := builder.Table(appoauththirdparty.Table)
	columns := aotpq.fields
	if len(columns) == 0 {
		columns = appoauththirdparty.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aotpq.sql != nil {
		selector = aotpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aotpq.unique != nil && *aotpq.unique {
		selector.Distinct()
	}
	for _, m := range aotpq.modifiers {
		m(selector)
	}
	for _, p := range aotpq.predicates {
		p(selector)
	}
	for _, p := range aotpq.order {
		p(selector)
	}
	if offset := aotpq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aotpq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (aotpq *AppOAuthThirdPartyQuery) ForUpdate(opts ...sql.LockOption) *AppOAuthThirdPartyQuery {
	if aotpq.driver.Dialect() == dialect.Postgres {
		aotpq.Unique(false)
	}
	aotpq.modifiers = append(aotpq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return aotpq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (aotpq *AppOAuthThirdPartyQuery) ForShare(opts ...sql.LockOption) *AppOAuthThirdPartyQuery {
	if aotpq.driver.Dialect() == dialect.Postgres {
		aotpq.Unique(false)
	}
	aotpq.modifiers = append(aotpq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return aotpq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (aotpq *AppOAuthThirdPartyQuery) Modify(modifiers ...func(s *sql.Selector)) *AppOAuthThirdPartySelect {
	aotpq.modifiers = append(aotpq.modifiers, modifiers...)
	return aotpq.Select()
}

// AppOAuthThirdPartyGroupBy is the group-by builder for AppOAuthThirdParty entities.
type AppOAuthThirdPartyGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aotpgb *AppOAuthThirdPartyGroupBy) Aggregate(fns ...AggregateFunc) *AppOAuthThirdPartyGroupBy {
	aotpgb.fns = append(aotpgb.fns, fns...)
	return aotpgb
}

// Scan applies the group-by query and scans the result into the given value.
func (aotpgb *AppOAuthThirdPartyGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := aotpgb.path(ctx)
	if err != nil {
		return err
	}
	aotpgb.sql = query
	return aotpgb.sqlScan(ctx, v)
}

func (aotpgb *AppOAuthThirdPartyGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range aotpgb.fields {
		if !appoauththirdparty.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := aotpgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aotpgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (aotpgb *AppOAuthThirdPartyGroupBy) sqlQuery() *sql.Selector {
	selector := aotpgb.sql.Select()
	aggregation := make([]string, 0, len(aotpgb.fns))
	for _, fn := range aotpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(aotpgb.fields)+len(aotpgb.fns))
		for _, f := range aotpgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(aotpgb.fields...)...)
}

// AppOAuthThirdPartySelect is the builder for selecting fields of AppOAuthThirdParty entities.
type AppOAuthThirdPartySelect struct {
	*AppOAuthThirdPartyQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (aotps *AppOAuthThirdPartySelect) Scan(ctx context.Context, v interface{}) error {
	if err := aotps.prepareQuery(ctx); err != nil {
		return err
	}
	aotps.sql = aotps.AppOAuthThirdPartyQuery.sqlQuery(ctx)
	return aotps.sqlScan(ctx, v)
}

func (aotps *AppOAuthThirdPartySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := aotps.sql.Query()
	if err := aotps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (aotps *AppOAuthThirdPartySelect) Modify(modifiers ...func(s *sql.Selector)) *AppOAuthThirdPartySelect {
	aotps.modifiers = append(aotps.modifiers, modifiers...)
	return aotps
}
