// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/appuser-middleware/pkg/db/ent/oauththirdparty"
	"github.com/NpoolPlatform/appuser-middleware/pkg/db/ent/predicate"
)

// OAuthThirdPartyDelete is the builder for deleting a OAuthThirdParty entity.
type OAuthThirdPartyDelete struct {
	config
	hooks    []Hook
	mutation *OAuthThirdPartyMutation
}

// Where appends a list predicates to the OAuthThirdPartyDelete builder.
func (otpd *OAuthThirdPartyDelete) Where(ps ...predicate.OAuthThirdParty) *OAuthThirdPartyDelete {
	otpd.mutation.Where(ps...)
	return otpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (otpd *OAuthThirdPartyDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(otpd.hooks) == 0 {
		affected, err = otpd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OAuthThirdPartyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			otpd.mutation = mutation
			affected, err = otpd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(otpd.hooks) - 1; i >= 0; i-- {
			if otpd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = otpd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, otpd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (otpd *OAuthThirdPartyDelete) ExecX(ctx context.Context) int {
	n, err := otpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (otpd *OAuthThirdPartyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: oauththirdparty.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: oauththirdparty.FieldID,
			},
		},
	}
	if ps := otpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, otpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// OAuthThirdPartyDeleteOne is the builder for deleting a single OAuthThirdParty entity.
type OAuthThirdPartyDeleteOne struct {
	otpd *OAuthThirdPartyDelete
}

// Exec executes the deletion query.
func (otpdo *OAuthThirdPartyDeleteOne) Exec(ctx context.Context) error {
	n, err := otpdo.otpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oauththirdparty.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (otpdo *OAuthThirdPartyDeleteOne) ExecX(ctx context.Context) {
	otpdo.otpd.ExecX(ctx)
}
