// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/appuser-middleware/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/appuser-middleware/pkg/db/ent/recoverycode"
)

// RecoveryCodeQuery is the builder for querying RecoveryCode entities.
type RecoveryCodeQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.RecoveryCode
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RecoveryCodeQuery builder.
func (rcq *RecoveryCodeQuery) Where(ps ...predicate.RecoveryCode) *RecoveryCodeQuery {
	rcq.predicates = append(rcq.predicates, ps...)
	return rcq
}

// Limit adds a limit step to the query.
func (rcq *RecoveryCodeQuery) Limit(limit int) *RecoveryCodeQuery {
	rcq.limit = &limit
	return rcq
}

// Offset adds an offset step to the query.
func (rcq *RecoveryCodeQuery) Offset(offset int) *RecoveryCodeQuery {
	rcq.offset = &offset
	return rcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rcq *RecoveryCodeQuery) Unique(unique bool) *RecoveryCodeQuery {
	rcq.unique = &unique
	return rcq
}

// Order adds an order step to the query.
func (rcq *RecoveryCodeQuery) Order(o ...OrderFunc) *RecoveryCodeQuery {
	rcq.order = append(rcq.order, o...)
	return rcq
}

// First returns the first RecoveryCode entity from the query.
// Returns a *NotFoundError when no RecoveryCode was found.
func (rcq *RecoveryCodeQuery) First(ctx context.Context) (*RecoveryCode, error) {
	nodes, err := rcq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{recoverycode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rcq *RecoveryCodeQuery) FirstX(ctx context.Context) *RecoveryCode {
	node, err := rcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RecoveryCode ID from the query.
// Returns a *NotFoundError when no RecoveryCode ID was found.
func (rcq *RecoveryCodeQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = rcq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{recoverycode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rcq *RecoveryCodeQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := rcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RecoveryCode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RecoveryCode entity is found.
// Returns a *NotFoundError when no RecoveryCode entities are found.
func (rcq *RecoveryCodeQuery) Only(ctx context.Context) (*RecoveryCode, error) {
	nodes, err := rcq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{recoverycode.Label}
	default:
		return nil, &NotSingularError{recoverycode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rcq *RecoveryCodeQuery) OnlyX(ctx context.Context) *RecoveryCode {
	node, err := rcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RecoveryCode ID in the query.
// Returns a *NotSingularError when more than one RecoveryCode ID is found.
// Returns a *NotFoundError when no entities are found.
func (rcq *RecoveryCodeQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = rcq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{recoverycode.Label}
	default:
		err = &NotSingularError{recoverycode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rcq *RecoveryCodeQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := rcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RecoveryCodes.
func (rcq *RecoveryCodeQuery) All(ctx context.Context) ([]*RecoveryCode, error) {
	if err := rcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rcq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rcq *RecoveryCodeQuery) AllX(ctx context.Context) []*RecoveryCode {
	nodes, err := rcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RecoveryCode IDs.
func (rcq *RecoveryCodeQuery) IDs(ctx context.Context) ([]uint32, error) {
	var ids []uint32
	if err := rcq.Select(recoverycode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rcq *RecoveryCodeQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := rcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rcq *RecoveryCodeQuery) Count(ctx context.Context) (int, error) {
	if err := rcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rcq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rcq *RecoveryCodeQuery) CountX(ctx context.Context) int {
	count, err := rcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rcq *RecoveryCodeQuery) Exist(ctx context.Context) (bool, error) {
	if err := rcq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rcq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rcq *RecoveryCodeQuery) ExistX(ctx context.Context) bool {
	exist, err := rcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RecoveryCodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rcq *RecoveryCodeQuery) Clone() *RecoveryCodeQuery {
	if rcq == nil {
		return nil
	}
	return &RecoveryCodeQuery{
		config:     rcq.config,
		limit:      rcq.limit,
		offset:     rcq.offset,
		order:      append([]OrderFunc{}, rcq.order...),
		predicates: append([]predicate.RecoveryCode{}, rcq.predicates...),
		// clone intermediate query.
		sql:    rcq.sql.Clone(),
		path:   rcq.path,
		unique: rcq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RecoveryCode.Query().
//		GroupBy(recoverycode.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (rcq *RecoveryCodeQuery) GroupBy(field string, fields ...string) *RecoveryCodeGroupBy {
	grbuild := &RecoveryCodeGroupBy{config: rcq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rcq.sqlQuery(ctx), nil
	}
	grbuild.label = recoverycode.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.RecoveryCode.Query().
//		Select(recoverycode.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (rcq *RecoveryCodeQuery) Select(fields ...string) *RecoveryCodeSelect {
	rcq.fields = append(rcq.fields, fields...)
	selbuild := &RecoveryCodeSelect{RecoveryCodeQuery: rcq}
	selbuild.label = recoverycode.Label
	selbuild.flds, selbuild.scan = &rcq.fields, selbuild.Scan
	return selbuild
}

func (rcq *RecoveryCodeQuery) prepareQuery(ctx context.Context) error {
	for _, f := range rcq.fields {
		if !recoverycode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rcq.path != nil {
		prev, err := rcq.path(ctx)
		if err != nil {
			return err
		}
		rcq.sql = prev
	}
	if recoverycode.Policy == nil {
		return errors.New("ent: uninitialized recoverycode.Policy (forgotten import ent/runtime?)")
	}
	if err := recoverycode.Policy.EvalQuery(ctx, rcq); err != nil {
		return err
	}
	return nil
}

func (rcq *RecoveryCodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RecoveryCode, error) {
	var (
		nodes = []*RecoveryCode{}
		_spec = rcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*RecoveryCode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &RecoveryCode{config: rcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(rcq.modifiers) > 0 {
		_spec.Modifiers = rcq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rcq *RecoveryCodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rcq.querySpec()
	if len(rcq.modifiers) > 0 {
		_spec.Modifiers = rcq.modifiers
	}
	_spec.Node.Columns = rcq.fields
	if len(rcq.fields) > 0 {
		_spec.Unique = rcq.unique != nil && *rcq.unique
	}
	return sqlgraph.CountNodes(ctx, rcq.driver, _spec)
}

func (rcq *RecoveryCodeQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := rcq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (rcq *RecoveryCodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   recoverycode.Table,
			Columns: recoverycode.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: recoverycode.FieldID,
			},
		},
		From:   rcq.sql,
		Unique: true,
	}
	if unique := rcq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rcq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recoverycode.FieldID)
		for i := range fields {
			if fields[i] != recoverycode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rcq *RecoveryCodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rcq.driver.Dialect())
	t1 := builder.Table(recoverycode.Table)
	columns := rcq.fields
	if len(columns) == 0 {
		columns = recoverycode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rcq.sql != nil {
		selector = rcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rcq.unique != nil && *rcq.unique {
		selector.Distinct()
	}
	for _, m := range rcq.modifiers {
		m(selector)
	}
	for _, p := range rcq.predicates {
		p(selector)
	}
	for _, p := range rcq.order {
		p(selector)
	}
	if offset := rcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (rcq *RecoveryCodeQuery) ForUpdate(opts ...sql.LockOption) *RecoveryCodeQuery {
	if rcq.driver.Dialect() == dialect.Postgres {
		rcq.Unique(false)
	}
	rcq.modifiers = append(rcq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return rcq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (rcq *RecoveryCodeQuery) ForShare(opts ...sql.LockOption) *RecoveryCodeQuery {
	if rcq.driver.Dialect() == dialect.Postgres {
		rcq.Unique(false)
	}
	rcq.modifiers = append(rcq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return rcq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rcq *RecoveryCodeQuery) Modify(modifiers ...func(s *sql.Selector)) *RecoveryCodeSelect {
	rcq.modifiers = append(rcq.modifiers, modifiers...)
	return rcq.Select()
}

// RecoveryCodeGroupBy is the group-by builder for RecoveryCode entities.
type RecoveryCodeGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rcgb *RecoveryCodeGroupBy) Aggregate(fns ...AggregateFunc) *RecoveryCodeGroupBy {
	rcgb.fns = append(rcgb.fns, fns...)
	return rcgb
}

// Scan applies the group-by query and scans the result into the given value.
func (rcgb *RecoveryCodeGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := rcgb.path(ctx)
	if err != nil {
		return err
	}
	rcgb.sql = query
	return rcgb.sqlScan(ctx, v)
}

func (rcgb *RecoveryCodeGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range rcgb.fields {
		if !recoverycode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rcgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rcgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rcgb *RecoveryCodeGroupBy) sqlQuery() *sql.Selector {
	selector := rcgb.sql.Select()
	aggregation := make([]string, 0, len(rcgb.fns))
	for _, fn := range rcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(rcgb.fields)+len(rcgb.fns))
		for _, f := range rcgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(rcgb.fields...)...)
}

// RecoveryCodeSelect is the builder for selecting fields of RecoveryCode entities.
type RecoveryCodeSelect struct {
	*RecoveryCodeQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (rcs *RecoveryCodeSelect) Scan(ctx context.Context, v interface{}) error {
	if err := rcs.prepareQuery(ctx); err != nil {
		return err
	}
	rcs.sql = rcs.RecoveryCodeQuery.sqlQuery(ctx)
	return rcs.sqlScan(ctx, v)
}

func (rcs *RecoveryCodeSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rcs.sql.Query()
	if err := rcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rcs *RecoveryCodeSelect) Modify(modifiers ...func(s *sql.Selector)) *RecoveryCodeSelect {
	rcs.modifiers = append(rcs.modifiers, modifiers...)
	return rcs
}
