// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/appuser-middleware/pkg/db/ent/recoverycode"
	"github.com/google/uuid"
)

// RecoveryCode is the model entity for the RecoveryCode schema.
type RecoveryCode struct {
	config `json:"-"`
	// ID of the ent.
	ID uint32 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt uint32 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt uint32 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt uint32 `json:"deleted_at,omitempty"`
	// EntID holds the value of the "ent_id" field.
	EntID uuid.UUID `json:"ent_id,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID uuid.UUID `json:"app_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Used holds the value of the "used" field.
	Used bool `json:"used,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RecoveryCode) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case recoverycode.FieldUsed:
			values[i] = new(sql.NullBool)
		case recoverycode.FieldID, recoverycode.FieldCreatedAt, recoverycode.FieldUpdatedAt, recoverycode.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case recoverycode.FieldCode:
			values[i] = new(sql.NullString)
		case recoverycode.FieldEntID, recoverycode.FieldAppID, recoverycode.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type RecoveryCode", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RecoveryCode fields.
func (rc *RecoveryCode) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recoverycode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rc.ID = uint32(value.Int64)
		case recoverycode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				rc.CreatedAt = uint32(value.Int64)
			}
		case recoverycode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				rc.UpdatedAt = uint32(value.Int64)
			}
		case recoverycode.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				rc.DeletedAt = uint32(value.Int64)
			}
		case recoverycode.FieldEntID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field ent_id", values[i])
			} else if value != nil {
				rc.EntID = *value
			}
		case recoverycode.FieldAppID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value != nil {
				rc.AppID = *value
			}
		case recoverycode.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				rc.UserID = *value
			}
		case recoverycode.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				rc.Code = value.String
			}
		case recoverycode.FieldUsed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field used", values[i])
			} else if value.Valid {
				rc.Used = value.Bool
			}
		}
	}
	return nil
}

// Update returns a builder for updating this RecoveryCode.
// Note that you need to call RecoveryCode.Unwrap() before calling this method if this RecoveryCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (rc *RecoveryCode) Update() *RecoveryCodeUpdateOne {
	return (&RecoveryCodeClient{config: rc.config}).UpdateOne(rc)
}

// Unwrap unwraps the RecoveryCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rc *RecoveryCode) Unwrap() *RecoveryCode {
	_tx, ok := rc.config.driver.(*txDriver)
	if !ok {
		panic("ent: RecoveryCode is not a transactional entity")
	}
	rc.config.driver = _tx.drv
	return rc
}

// String implements the fmt.Stringer.
func (rc *RecoveryCode) String() string {
	var builder strings.Builder
	builder.WriteString("RecoveryCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rc.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", rc.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", rc.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", rc.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("ent_id=")
	builder.WriteString(fmt.Sprintf("%v", rc.EntID))
	builder.WriteString(", ")
	builder.WriteString("app_id=")
	builder.WriteString(fmt.Sprintf("%v", rc.AppID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", rc.UserID))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(rc.Code)
	builder.WriteString(", ")
	builder.WriteString("used=")
	builder.WriteString(fmt.Sprintf("%v", rc.Used))
	builder.WriteByte(')')
	return builder.String()
}

// RecoveryCodes is a parsable slice of RecoveryCode.
type RecoveryCodes []*RecoveryCode

func (rc RecoveryCodes) config(cfg config) {
	for _i := range rc {
		rc[_i].config = cfg
	}
}
